### PR TITLE
Exported the 2 layers of the PCB as PNGs so people don't need a PCB tool to view them

### PR DESCRIPTION
**Pull request by adamtegen**

### CODE REVIEW

**Comment by RudolphRiedel** [comment]
PNG is a pixel-format, you can not zoom it like a vector drawing in a .pdf.
And Ender3_pcb_parts.PDF does not only contain the top-layer besides all parts, it is a vector drawing.
If there is need for it I could provide an updated version with more information and also fix that German that sneaked into it with my default settings. :-)

Heck, why wait, here you go:
[Ender3_pcb_parts.PDF](https://github.com/Creality3DPrinting/Ender-3/files/2307259/Ender3_pcb_parts.PDF)

**Comment by adamtegen** [comment]
@RudolphRiedel For some reason, the file you linked me has all the layers and is 2.6MB.  The one in the repo ( https://github.com/Creality3DPrinting/Ender-3/blob/master/Ender-3%20PCB/Ender3_pcb_parts.PDF )  is only the top layer and is only 671KB.  Any idea why the full version isn't the only in master/PCB?

**Comment by RudolphRiedel** [comment]
>Gerber files would be better.

Here you go, a fresh set of gerber and drill files: 
[Ender3 PCB Gerber.zip](https://github.com/Creality3DPrinting/Ender-3/files/2308026/Ender3.PCB.Gerber.zip)

> For some reason, the file you linked me has all the layers and is 2.6MB.

The reason ist that I just created and uploaded the pdf from the PCB data. :-)

**Comment by steenerson** [comment]
I have updated the PDF with the above version with both layers and the part overlay, thanks @RudolphRiedel and @adamtegen ! The vector PDF format is best and I think adding PNG format would be duplicate info so I'm closing this PR.

**Pull request closed without merging**
